spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  case-event-exchange: events
  fulfilment-routing-key: event.fulfilment.request
  fulfilment-request-inbound-queue: notify.fulfilments
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/notify-processor-healthy

notify:
  apiKey: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
  baseUrl: https://dummy-notify:123
  testMode: true
  templateIdReplacementHHE: 21447bc2-e7c7-41ba-8c5e-7a5893068525
  templateIdReplacementHHW: ef045f43-ffa8-4047-b8e2-65bfbce0f026
  templateIdReplacementHHNI: 23f96daf-9674-4087-acfc-ffe98a52cf16
  templateIdIndividualResponseE: 1ccd02a4-9b90-4234-ab7a-9215cb498f14
  templateIdIndividualResponseW: 12dbc690-dc0e-4830-90bb-8a7d2282a521
  templateIdIndividualResponseNI: eeed8619-2510-4871-a8c5-b442f574c358
  senderId: b7e75a6c-8f7f-4264-8b34-38bb5831270e

caseapi:
  host: case-api
  port: 80
