spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  fulfilment-routing-key: event.fulfilment.request
  fulfilment-request-inbound-queue: notify.fulfilments
  enriched-fulfilment-exchange: notify.enriched.fulfilment.exchange
  enriched-fulfilment-queue: notify.enriched.fulfilment
  uac-qid-created-exchange: uac-qid-created-exchange
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/notify-processor-healthy

notify:
  apiKey: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
  baseUrl: https://dummy-notify:123
  templateEnglishHouseHold: ce1e545e-f50f-455b-a394-88b49a36fa0c
  templateWelshHouseHold: 67dc02ff-a667-4b21-8e4e-61dd28936b8c
  templateWelshAndEnglishHouseHold: 2375c493-359d-4712-938e-bf97a641f18f
  templateNorthernIrelandHouseHold: 5d985237-b446-492a-bd0a-f7368265282c
  templateEnglishIndividualResponse: b7ec0cde-b55b-460a-a78a-cb80767acdca
  templateWelshIndividualResponse: b2db05f0-d7d1-4b88-b3de-658495bd8a47
  templateWelshAndEnglishIndividualResponse: f6de09f2-4d4c-4f62-82e3-b1a24e0cf910
  templateNorthernIrelandIndividualResponse: d490af7d-300a-4eb8-a961-cb4de54332ee
  templateEnglishCe: 21f22f8d-2642-444e-9d13-a54b87647a93
  templateWelshCe: 2c12a125-4035-4b81-9988-204e02e759a5
  templateWelshAndEnglishCe: b2b9e650-cb22-49d7-b5da-95169e13ea12
  senderId: ae14c5b3-f317-4051-834c-644f0c236347

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 5   #seconds

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR