spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  case-event-exchange: events
  fulfilment-routing-key: event.fulfilment.request
  fulfilment-request-inbound-queue: notify.fulfilments
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/notify-processor-healthy

notify:
  apiKey: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
  baseUrl: https://dummy-notify:123
  testMode: true
  templateIdReplacementHH: b002e875-1176-423d-ac38-31c7781b7b6e
  templateIdIndividualResponse: 665c66e2-dd16-4f08-83cf-bde2decd4729
  senderId: cd2c82c3-a9ff-4915-bb71-f9eddeab2a26

caseapi:
  host: localhost
  port: 8161
